### PR TITLE
Allow specifying custom Auth0 lock config

### PR DESCRIPTION
**Pull request by evansiroky**
- expose new property lock on the Auth0 component that enables setting
a custom lock
- add tests
- refactor tests to match directory structure

### CODE REVIEW

**Comment by evansiroky** [comment]
Well, there are actions that get dispatched, not sure how to do that without a store.

**Comment by trevorgerhardt** [comment]
Change the `export const lock = ...` to a `getLock` function and pass the configuration data. Everything you want to set is [here](https://github.com/conveyal/woonerf/blob/dev/src/auth0.js#L15) right? Just an Auth0Lock configuration object? 

Also, does the lock itself actually dispatch anything?

**Comment by evansiroky** [comment]
The lock doesn't dispatch stuff, but it in the Auth0 component of woonerf the authentication handler will dispatch stuff.

Were you thinking something along the lines of creating the lock in the componentWillMount method?

**Comment by trevorgerhardt** [comment]
@evansiroky yup

**Pull request merged**
