### PR TITLE
Pass the store to the mounted app component

### PR DESCRIPTION
**Pull request by trevorgerhardt**
Useful for bootstrapping.

### CODE REVIEW

**Comment by evansiroky** [comment]
This PR might be a good opportunity to expand upon the README's documentation of mount.

**Comment by trevorgerhardt** [comment]
@evansiroky good call, please review 👌

**Comment by evansiroky** [comment]
There is another section in the `api` bullet list called `mount` close to the bottom of the README.  Should we get rid of that?

**Comment by trevorgerhardt** [comment]
@evansiroky yea, it's explained in the usage section.

**Comment by trevorgerhardt** [comment]
removed

**Comment by evansiroky** [comment]
gotta change the table of contents too

**Pull request merged**
